### ISSUE TITLE
Light switches off when a new minute starts

### ISSUE THREAD

**Issue by iNorD** [maros/Zway-AutoOffInactive#2]
Light switches off when a new minute starts.
Example: motion detected 12:05:22, light turns on automatically. And turns off at 12:06:00
Parameters:
timeout 15
sensor: fibaro motion
switch fibaro dimmer

**Comment by maros** [comment]
Could you please provide the content of /var/log/z-way-server.log when this happens.
grep 'AutoOffInactive' -C10 /var/log/z-way-server.log

Please also note that for the trigger use-case i'd rather recommend my MotionTrigger module.

**Comment by iNorD** [comment]
Oh, it works now. The problem was that after installing base module you need to reboot your raspberry and then install other modules.
